# Generated by Django 6.0.3 on 2026-03-15 09:16

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user_agent', models.TextField(blank=True, default='')),
                ('keyboard_type', models.CharField(blank=True, default='unknown', max_length=50)),
                ('status', models.CharField(default='active', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='PredictionResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('openness', models.FloatField()),
                ('conscientiousness', models.FloatField()),
                ('extraversion', models.FloatField()),
                ('agreeableness', models.FloatField()),
                ('neuroticism', models.FloatField()),
                ('features_json', models.JSONField(default=dict)),
                ('explanations_json', models.JSONField(default=dict)),
                ('model_version', models.CharField(default='xgb_v1', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='prediction', to='api.session')),
            ],
        ),
        migrations.CreateModel(
            name='KeystrokeEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(max_length=50)),
                ('event_type', models.CharField(max_length=10)),
                ('key', models.CharField(max_length=50)),
                ('code', models.CharField(max_length=50)),
                ('timestamp', models.FloatField()),
                ('is_repeat', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='api.session')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
    ]
