# Generated by Django 6.0.3 on 2026-03-16 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='predictionresult',
            name='emotion_arousal',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='predictionresult',
            name='emotion_label',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='predictionresult',
            name='emotion_scores_json',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='predictionresult',
            name='emotion_valence',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
